# Generated by Django 3.2.7 on 2022-06-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_User_name', models.CharField(max_length=30, verbose_name='名前')),
                ('Report_User_dept', models.CharField(max_length=30, verbose_name='部署')),
                ('Report_User_area', models.CharField(max_length=30, verbose_name='エリア')),
                ('Report_Row_date', models.CharField(blank=True, max_length=30, null=True, verbose_name='日付')),
                ('Report_Matter_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='工番')),
                ('Report_Work_class', models.CharField(blank=True, max_length=30, null=True, verbose_name='作業区分')),
                ('Report_Work_contents', models.CharField(blank=True, max_length=30, null=True, verbose_name='作業番号')),
                ('Report_Rowstart_time', models.TimeField(max_length=30, verbose_name='開始時間')),
                ('Report_Rowend_time', models.TimeField(max_length=30, verbose_name='終了時間')),
                ('Report_Total_time', models.IntegerField(verbose_name='所要時間')),
                ('Report_Over_time', models.IntegerField(blank=True, null=True, verbose_name='残業時間')),
                ('Report_Night_time', models.IntegerField(blank=True, null=True, verbose_name='夜勤時間')),
                ('Report_Check_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='チェック')),
            ],
        ),
    ]
