# Generated by Django 3.2.7 on 2022-05-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='Report_User_area',
            field=models.CharField(default=1, max_length=30, verbose_name='エリア'),
            preserve_default=False,
        ),
    ]
