# Generated by Django 3.2.7 on 2022-04-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kintone_domain', models.CharField(max_length=30, verbose_name='ドメイン')),
                ('kintone_input_API', models.CharField(max_length=50, verbose_name='入力API')),
                ('kintone_input_appID', models.CharField(max_length=3, verbose_name='入力アプリID')),
                ('kintone_output_API', models.CharField(max_length=50, verbose_name='出力API')),
                ('kintone_output_appID', models.CharField(max_length=3, verbose_name='出力アプリID')),
                ('matter_update_number', models.CharField(max_length=5, verbose_name='工番更新頻度')),
            ],
        ),
        migrations.CreateModel(
            name='Matter_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='工番')),
                ('matter_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='案件名')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='取引名')),
                ('matter_deadline', models.DateField(blank=True, null=True, verbose_name='納期')),
                ('matter_displayinfo', models.IntegerField(blank=True, null=True, verbose_name='表示情報')),
            ],
        ),
        migrations.CreateModel(
            name='User_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='番号')),
                ('area', models.CharField(max_length=10, verbose_name='場所')),
            ],
        ),
        migrations.CreateModel(
            name='User_Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='番号')),
                ('dept', models.CharField(max_length=30, verbose_name='部署')),
            ],
        ),
        migrations.CreateModel(
            name='DefaulWorkContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=50, verbose_name='作業内容')),
                ('number', models.IntegerField(verbose_name='番号')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_setting.user_dept')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultWorkclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=50, verbose_name='作業区分')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_setting.user_dept')),
            ],
        ),
    ]
