# Generated by Django 3.2.7 on 2022-04-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kintone_setting_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kintone_domain', models.CharField(max_length=30, verbose_name='ドメイン')),
                ('kintone_input_API', models.CharField(max_length=50, verbose_name='入力API')),
                ('kintone_input_appID', models.CharField(max_length=3, verbose_name='入力アプリID')),
                ('kintone_output_API', models.CharField(max_length=50, verbose_name='出力API')),
                ('kintone_output_appID', models.CharField(max_length=3, verbose_name='出力アプリID')),
                ('matter_update_number', models.CharField(max_length=5, verbose_name='工番更新頻度')),
                ('automation_update_mode', models.IntegerField(verbose_name='自動取得')),
            ],
        ),
        migrations.DeleteModel(
            name='App_setting',
        ),
    ]
