# Generated by Django 3.2.7 on 2021-11-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matter_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='工番')),
                ('matter_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='案件名')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='取引名')),
                ('progress', models.CharField(blank=True, max_length=100, null=True, verbose_name='進捗状況')),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('constr_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='工番')),
                ('work_class', models.CharField(max_length=30, verbose_name='作業区分')),
                ('work_class_detail', models.TextField(blank=True, null=True, verbose_name='作業区分詳細')),
                ('work_contents', models.CharField(max_length=30, verbose_name='作業番号')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('total_time', models.IntegerField(blank=True, null=True, verbose_name='所要時間')),
                ('check_number', models.IntegerField(default=1, null=True, verbose_name='チェック')),
            ],
        ),
        migrations.CreateModel(
            name='Work_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_Class', models.CharField(blank=True, max_length=30, null=True, verbose_name='作業区分')),
            ],
        ),
        migrations.CreateModel(
            name='Work_contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contents', models.CharField(blank=True, max_length=30, null=True, verbose_name='作業内容')),
                ('Work_Contents_number', models.IntegerField(blank=True, null=True, verbose_name='番号')),
            ],
        ),
    ]
