# Generated by Django 3.2.7 on 2021-10-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_contents',
            name='Work_Contents_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
