# Generated by Django 3.2.7 on 2021-11-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='end_time',
            field=models.TimeField(verbose_name='終了時間'),
        ),
    ]
