# Generated by Django 3.2.7 on 2021-10-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_work_contents_work_contents_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter_code',
            name='matter_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
