# Generated by Django 3.2.7 on 2021-10-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_matter_code_matter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter_code',
            name='matter_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
