# Generated by Django 3.2.7 on 2021-11-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_matter_code_matter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='check_number',
            field=models.IntegerField(default=1),
        ),
    ]
