# Generated by Django 3.2.7 on 2021-11-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_reports_check_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='check_number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
