# Generated by Django 3.2.7 on 2021-11-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_reports_check_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='constr_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='work_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='work_contents',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
