# Generated by Django 3.2.7 on 2021-11-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20211104_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter_code',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='取引名'),
        ),
        migrations.AlterField(
            model_name='matter_code',
            name='matter_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='工番'),
        ),
        migrations.AlterField(
            model_name='matter_code',
            name='matter_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='案件名'),
        ),
        migrations.AlterField(
            model_name='matter_code',
            name='progress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='進捗状況'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='check_number',
            field=models.IntegerField(default=1, null=True, verbose_name='チェック'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='constr_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='工番'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='work_class',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='作業区分'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='work_class_detail',
            field=models.TextField(blank=True, null=True, verbose_name='作業区分詳細'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='work_contents',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='作業番号'),
        ),
        migrations.AlterField(
            model_name='work_class',
            name='Work_Class',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='作業区分'),
        ),
        migrations.AlterField(
            model_name='work_contents',
            name='Contents',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='作業内容'),
        ),
        migrations.AlterField(
            model_name='work_contents',
            name='Work_Contents_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='番号'),
        ),
    ]
