# Generated by Django 3.2.7 on 2021-11-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20211105_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='total_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='所要時間'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='end_time',
            field=models.TimeField(verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='start_time',
            field=models.TimeField(verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='work_class',
            field=models.CharField(max_length=30, verbose_name='作業区分'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='work_contents',
            field=models.CharField(max_length=30, verbose_name='作業番号'),
        ),
    ]
