# Generated by Django 3.2.7 on 2021-11-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20211110_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時間'),
        ),
    ]
